#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: post
title: Can an indie scientist get funding to run a real lab?
date: 2016-04-18 19:38
# Should be longer than 150 words, so it will appear as post summary
description: Even if you bootstrap your way into a genuine scientific education and a minimal lab, can you make a full-time living as an independent researcher?
# tags will also be used as html meta keywords.
tags:
  - synthetic biology

show_meta: true
comments: true
mathjax: true
gistembed: true
published: true
noindex: false
nofollow: false
---
#+END_HTML
#+TOC: headlines 2

In my last post I looked at a full-stack approach to open science - getting up and running
as that rarest of birds, the self-educated indie scientist. Long thought to have gone extinct in the Victorian
era, some believe the "gentleman scientist" - gentleperson, surely? - may be due for a comeback.

Is this actually a viable approach for someone who wants to do more than vanity research?
I'll assume for the moment that we're talking about someone who has the emotional support, the motivation,
the intellectual firepower, and the good sense to do quality work, bearing in mind that many practicing 
scientists lack one or more of these qualities.

In that case, it comes down to lab equipment, space, and living resources. Or, in other words, money, money, and money.

What is the state of the field for getting funding? Well, there's bad news, and then there's more bad news.

The National Institutes of Health makes government science grants, and if you're looking for millions they're the place
to get it. However, NIH grants require applicants to [[https://www.niaid.nih.gov/researchfunding/grant/strategy/pages/1qualify.aspx][have a Ph.D.]] as well as substantial experience in administering a
lab and publishing research. In fact, government funding is working on reducing the time it
takes for a postdoc to receive their first major grant. That's their major innovation. If a postdoctoral researcher has
a tough time getting funding to open her own lab, an independent researcher without a Ph.D. will find it even more difficult.

If you want to do top-tier research, then, you'd better go where the smart people, and big money is: academia.
Right? Probably, but here's more bad news. As [[http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2685175/][How to succeed in science: a concise guide for young biomedical scientists]] points
out, the average age at which a postdoc receives a major grant is 43. That's for someone who went straight through grad school,
I presume. [[http://www.sciencemag.org/careers/2009/07/independent-postdocs-resources][Science]] and [[http://blogs.nature.com/naturejobs/2015/03/30/the-postdoc-series-finding-funding/][Nature]] discuss some of the problems a postdoc faces in moving out on her own. The "concise guide" above
notes that it really did use to be easier thirty or forty years ago.

Even under the relatively pro-science - in economic terms - Obama administration, the funding for science has remained flat.
Because this flatlining follows a small boom, the field is now glutted with postdoctoral researchers: the [[http://www.motherjones.com/environment/2014/03/inquiring-minds-ethan-perlstein-postdocalypse]["Postdocalypse"]].

Now, if you do get a lab up and running, unaffiliated with a university or hospital, you have the advantage of
nimbleness, which may help you to generate results faster, and result in a better track record of getting
funding. Or that was the [[http://www.the-scientist.com/?articles.view/articleNo/10178/title/NIH-Funding--Independent-Labs-Have-Best-Success-Rate/][case 30 years ago, anyway.]]

Okay, if the big money goes to established researchers, and it's very hard to become one, how about the prospects
as an indie researcher?

Let's start by pointing out the obvious, as [[https://www.quora.com/What-is-it-like-to-be-an-indie-scientist][Quora post]] does well. Although an independent research theoretically has more
research freedom by not worrying about grant proposals and restrictions, and freedom from bureaucratic administration,
lack of time, money, and equipment make going indie very hard.

Very few people become indie researchers, and "citizen science" doesn't do hard, cutting-edge science.
I'm sure training and funding are the major reasons for this, but again let's stick to funding and assume
you can self-train ([[https://www.quora.com/How-does-one-get-started-as-an-independent-researcher][like this]]).

[[http://brightworkcoresearch.com/postdocalypse-opportunity-disguise/][Some]] hope the postdocalypse could be a biotech boom opportunity in disguise. [[http://www.sciencemag.org/careers/2013/05/going-rogue][Ethan Perlstein]] couldn't find an acadmic
position despite sterling Ivy-league credentials, and decided to crowdfund his work before forming
a [[http://www.plab.co/][public benefit corporation]] to continue researching "orphan diseases".

(A public benefit corporation is a very interesting profit-nonprofit hybrid, in which the corporate officers balance duties to mission and to profit)

More broadly, others argue the dual rise of crowdfunding and cheaper tools will pave the way for [[http://www.theguardian.com/higher-education-network/blog/2014/jun/16/diy-labs-exciting-alternative-university-science-research][an alternative to the university system]]
of doing science, and allow more people [[http://brightworkcoresearch.com/how-does-one-get-started-as-an-independent-researcher/][to get started as independent researchers]].

Rhiannon argues that science funding may be diversifying. Private grant-giving institutions and patrons
such as Peter Thiel, Facebook guy, Elon Musk, and Y Combinator prefer to give to non-government labs - 
a good sign for independent researchers. If government grantors follow suit - and there are some indications
that they are - then both funding, and active scientists, will become more diverse.

Are these resources sufficient for a full-time researcher to live on and build a private lab? 
That's a tough sell, but maybe.

- If you identify as a [[https://www.zooniverse.org/][citizen scientist]], you have a [[http://www.citizensciencecenter.com/citizen-science-funding/][couple]] of [[http://www.grants.gov/web/grants/search-grants.html?keywords=citizen%20science][resources]] to investigate.

- Entrepreneurship is always an option. Nobelist Peter Mitchell, Craig Venter, Stephen Wolfram, Ray Kurzweil, and 
Ethan Perlstein all became independent researchers, funding their work through entrepreneurship or other means 
(Venter combined entrepreneurship with staggeringly large NIH grants).

- Much of it come down to whether you can get access to slighly larger amounts of money.
I don't really know whether, with the assistance of [[https://www.instrumentl.com/][Instrumentl]], or quasi-grant institutions 
like [[http://www.breakoutlabs.org/][BreakoutLabs]], or [[http://oedb.org/ilibrarian/100_places_to_find_funding_your_research/][other grantors]], one can move beyond [[https://www.rockethub.com/][RocketHub]] or Experiment. (I also don't know whether
the NSF's standards are as restrictive as the NIH's).

For synthetic biology, funding [[http://www.synbioproject.org/publications/u.s-trends-in-synthetic-biology-research-funding/][may increase]] in the future. *But the present remains uncertain.*

