#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: post
title: "Book Review: Life at the Speed of Light"
date: 2016-04-12 12:47
# Should be longer than 150 words, so it will appear as post summary
description: "Venter's second book focuses more on the history and science of genomics and synthetic biology, as well as promises and perils. A little dryer than the autobiography, but a good read."
# tags will also be used as html meta keywords.
tags:
  - synthetic biology

show_meta: true
comments: true
mathjax: true
gistembed: true
published: true
noindex: false
nofollow: false
---
#+END_HTML
#+TOC: headlines 2

*** What is life?
To oversimplify this book, Venter has two themes. The first is a meditation on the
history of mankind's exploration of Schrödinger's question. Venter believes his research
has put paid to any mystical notions of "vitalism." Venter and his team were able
to transcribe a genome with complete accuracy, and then "print off" that genome.
The round-trip from chemistry to information and back again shows what life is: chemistry and information.

The second theme is that because life can be printed to digital media, we can now edit
and communicate life information at the speed of light. We're entering a new era of
humanity's quest to control life!

*** Venter's work
Much of the book details his team's laborious work to transcribe a bacterial genome
with complete accuracy, as the slightest error meant the bacteria would die, and then to edit
this genome and "boot it up" within a cell. Because genomes have "punctuation,"
three-letter sequences that guide transcription but don't actually contribute to a gene's
substance, Venter's team replaced the punctuation with a code they devised. This code
spelled out their names and several apposite quotations.

During this decade-long quest, Venter and his team made several extraordinary leaps in technique,
several of which radically increased speed and decreased cost, and are now used by teams the world over.

*** iGEM
Venter reserves perhaps his warmest words for the international educational phenomenon,
iGEM. Hundreds of undergraduate and community teams from all over the world conduct 
groundbreaking research and design every year, along with ethical and societal impacts analyses.

This warms the cockles of Venter's heart, as you may say, and no wonder. iGEM just might
be the most dynamic educational event on the planet. It gives Venter - and me - a lot of hope for
our future.

*** Mars

Venter firmly believes that there is life on Mars, based in part on his sequencing
of deep-cave-dwelling bacteria. Earth has more life forms below than above the surface!
While Mars receives too much surface radiation for life to survive on the surface,
it probably has deep reserves of water where bacteria could live.

This possibility ties in with the digital life theme. A future Mars rover
with access to water, and carrying a small sequencer (which already exist) would
be able to send back genomes digitally, thereby avoiding the profound difficulties
and fears associated with physically transporting a Martian bacteria.

*** The Precautionary Principle
Venter was proactive in seeking ethical review, a canny political move that has allowed
him to forestall bioethicists and religious leaders who might otherwise seek to ban the
entire line of research.

Venter refers to "low-probability, high-impact" events while avoiding naming Nassim Taleb by name.
To be fair, many other people seem to subscribe to a strong form of precautionary principle.
Unless you know the experiment is safe, don't do it, they say. 

With Venter, I think the blind application of this principle harms progress more than it aids society.
Humans have engaged in genetic modification since the Agricultural Revolution.
Food and fuel shortages, old age and diseases, climate change: these are known and intolerable harms.
We need to balance safety and progress, and chanting "precautionary principle" lacks all balance.

Frankly, this part of the book is rather dry - he walks through several government reports
he commissioned or participated in. Despite the bureaucratic language, the upshot is important
and encouraging: the government won't ban this research. The government and the rapidly-expanding
community of synthetic biologists can consider additional safety measures on a rolling, as-needed
basis.

*** The Nobel Prize
I've seen other reviews characterize this book as a pitch for Venter to win the Nobel Prize.
I frankly think that's just lazy journalism. Cutting straight to motives and alleged arrogance while ignoring the actual
science is a cheap way to write a more exciting article, without doing the hard work of explaining
why the science affects our humanity.

Still, if you counted the most-used words in this book, "Nobel Prize" would be right up there.
Venter clearly believes his work relies directly on and extends previous world-class work.

His autobiography, /A Life Decoded/, had already convinced me of that. There are several Nobel Prizes
due in the area of synthetic biology (Emmanuelle Charpentier and Jennifer Doudna, to name two),
and Venter should get one.
