#+BEGIN_HTML
---
layout: post
title: Book Review: A Life Decoded
date: 2016-04-09 12:42
description: "A quick overview of one of the most exciting stories of modern science"
# tags will also be used as html meta keywords.
tags:
  - synthetic biology

show_meta: true
comments: true
mathjax: true
gistembed: true
published: true
noindex: false
nofollow: false
---
#+END_HTML

* Book Review: A Life Decoded
"How did Venter manage to get all that science done? How did he garner private and public
resources sufficient to race the government-backed Human Genome Project to the finish,
when many aspiring scientsts can't even get their own labs?"
//
To answer that question, yesterday I picked up Craig Venter's first autobiography, /A Life Decoded/,
stayed up late reading it, and finished this morning.
//
*** Early Life
Venter grew up a happy kid, building stuff, playing around, and surfing.
Drafted into the Army, he rushed into the Navy, where his high IQ score allowed him 
to become a corpsman. Finagling paperwork got him a job /not/ on the front lines in Vietnam,
which saved his life. Vietnam was full of men gettin high for a temporary escape from
the horrors around them; Venter tried to commit suicide at one point.
//
Back in the states, Venter started attending community college, transferred to UCSD,
impressed a professor, and was actually given a lab. 
//
In grad school, Venter published a dozen papers and got his Ph.D. in only three years,
while most peers publish two papers after four or five years. There's not really any indication about how
Venter was able to choose so many winning experiments, but he did, and got good academic jobs out of the gate,
before moving to the National Institutes of Health. Basically, he was a rock star out of the gate.
//
The NIH is one of the premier government science organizations. Venter became pretty good at playing their bureaucratic games,
and continued to "move fast and break things." He took nearly ten years to sequence a single gene,
and as a result grabbed unproven automatic gene sequencing machines as soon as they became available.
//
His experience with automation prepared him to move to the private sector. Shockingly (to a lawyer), he
left his NIH position after his investors had prepared only a term sheet, not a final agreement.
On the other hand, this naïveté rebuts the money-grubbing reputation his opponents attributed to him.
//
*** Hard-ball Science
Anyone who's considered science grad school and read a few blogs knows of the petty corruption that a
bad thesis advisor can inflict on a doctoral candidate: too much work which doesn't advance your career
or interests, abusive behavior, long hours.
//
It turns out that corruption in science goes far beyond that. While Venter was in grad school at UCSD,
another professor /took advantage of his advisor's heart attack/ to steal their grant application.
She simply replaced Venter's and his advisor's names with her own and sent it in.
Once recovered, Venter's advisor refused to take any action to avoid ruining her career.
//
Hoarding data to prevent anyone else from using it sounds like almost the norm.
Demanding authorship on a paper for a non-scholarly favor is commonplace.
Moral: You need to be tough just to get your normal research done.
//
Moving up the ladder of corruption, the vicious years-long battle between Venter and the public effort
confirms what I've heard before: "Venter turned over the gravy train of public funding. A lot of scientists
had planned to live off that for a long, long time."
//
*** Money, money, money
This is really a hell of a story. The race betwen the private and public sectors
became a morality play centering around gene patenting and scientific methods.
//
Venter's backers were attempting to patent as many genes as possible,
and constantly fighting with Venter to attempt to prevent him from publishing the genes.
To the public sector - a consortium of labs with public funding dispersed by Francis Collins -
this mean Venter was a land-grabber, attempting to wall off the common heritage of all humankind.
//
In fact, (a) private companies were patenting the public effort's genes as well,
(b) Venter's next company gave up on patenting genes altogether, instead selling
access to a value-added database (think 23andme), (c) the public effort kept much data hidden anyway,
and (d) Venter's publication terms forbid commercial use and not academic use.
//
Venter realized that instead of reading off every A, T, G, and C in the entire genome,
he could focus on messenger RNA - the parts where the genome actually tells something
to get built. Those would be the genes, the parts of the code that direct the formation
of the proteins out of which we're made.
//
This struck the public sector as immoral. Would you helicopter to the top of Everest?
//
The public-private feud became pretty vicious. Collins cut off funding for anyone
who cooperated with Venter.
//
Still, it seems that part of the reason Venter decided to make a public announcement
along with the public effort was that he feared NIH would lose public credibility and hence funding.
In other words, all the scientists banded together to keep the money flowing in the future.

*** Lessons Learned
The casual reader will learn much about the history of the technology of gene sequencing,
and thus the terminology of those techniques.
//
I also learned much about how scientists get funding for their work. If you're lucky and convince the right public
or private backers, you can get a lot of money to do very good work.
//
The politics of data, money, and authorship are pervasive and rough, but if you play fair
and surround yourself with good people life can be good.
//
In science, new techniques are better than data, and data better than ideas, and ideas better than force of personal authority.
//
In science as in entrepreneurship, picking a good idea is necessary but not sufficient; it comes down to execution.
//
Many, perhaps the majority, of scientists are quite conservative. Mindful that a bad bet can wreck a career, they don't
like risky experiments. Venter speculates repeatedly about where he gets his risk-seeking behavior,
and what he's talking about in part is his repeated choice to just do the damn experiment and seek what comes of it.
With that said, he does seem to have chosen winning horses over and over again.

*** Life at the Speed of Light
Most of all, I like Venter's breakneck speed. He wants to get as much done as he can, as quickly as he can.
Yes, he nearly became a billionaire as well - there's a lot of money in science for a few at the top! - but
it's clear that he treasures most the thrill of discovery and of publication.


