#+OPTIONS: toc:nil
#+BEGIN_HTML
---
layout: post
title: Arguments for and against a doctoral program
date: 2016-04-23 13:17
# Should be longer than 150 words, so it will appear as post summary
description: In this post, I'm summarising my latest thoughts on whether to get a Ph.D., a topic worth considering in depth!
# tags will also be used as html meta keywords.
tags:
  - synthetic biology

show_meta: true
comments: true
mathjax: true
gistembed: true
published: true
noindex: false
nofollow: false
---
#+END_HTML
#+TOC: headlines 2

*** The goal is to do aging research, possibly via synthetic biology.
That requires a lab, funding, and education and training.

The options are: 
- get a Ph.D. and then work in a government-funded, university-affiliated lab; 
- get a Ph.D. and start a biotech company; start a biotech company and use the lab and money to fund research; 
- start any other sort of company and use the money to fund research.

*** Timeline
Any path to researching aging, any working on synthetic biology, must take nearly
a decade. 

Realistically, I cannot gain access to a good graduate program without all the
prerequisites, and some good publications. I cannot accomplish that by Fall 2017,
unless I begin going to school full-time, and even then not in time for an application.
Therefore, Fall 2018 is the earliest I could get into a grad program.

In that case, my choices are full-time study, or part-time study.
With part-time study, I can do a master's in math, starting Fall 2018.
(UT Austin's ICEs program looks very cool)
With full-time study, I could do a life sciences Ph.D., starting Fall 2018.

With part-time study and then a master's, I could also start a company.
As the company would extend beyond the master's, I could then do a physical or 
life sciences master's as well. 

Therefore, a decade hence, I have two master's and a company, or a Ph.D.
Will the credibility and expertise of the Ph.D. prove so valuable to my research?

If the research is best accomplished in a government-grant-funded, university-affiliated lab,
then yes. If not, then possibly not.

If no investor or employee or co-founder in their right minds would let me near a lab,
then yes. If I can have more control, then probably not.

*** Assorted Arguments
- Resources arguments: With a Ph.D., I'd have credibility and access to grant money.
- The "timeline argument": see above. A Ph.D. is not a shortcut.
- The parade of horribles: a Ph.D. is a horrible experience. You are poor, at the whims
of others, you flounder around looking for something to research, you'll never finish,
you won't have a job.
- Argument from learning: It's easy to underestimate just how much there is to know.
- Lab techniques, math, biochemistry, molbio: this will take years to learn. 
We can't start completely ignorant.

I feel entitled to disregard the parade of horribles, as I watched it go by before
attending law school, and I'm not unmotivated (perhaps most grad students are motivated,
but some are not).

*** Chances of success
Those arguments are pros and cons. They do not assess chances of success.
Next, the chances of succeeding in any startup are quite low. However, the chances
of receiving government funding to get a lab are also quite low, and typically occurs
around 43. As a star, I could hope to get funding much faster, but that depends on being a star.

My chances of getting into a quality grad program by Fall 2018 are probably pretty good.
By taking the prerequisites, and working DIYbio-style and then publishing on the side,
I'd look very motivated.

My chances of being a star depend on day-to-day enjoyment, and the competition.
Daily motivation is unknown. On the one hand I do get bored, on the other hand the work
sounds similar to what I do daily anyway. The competition will be high, but it was high
in law school as well, and I excelled half-motivated in law school.
Moderately good chances of being a star.

Startup success depends on high motivation, a market, ability to produce a money-earning
MVP, and so on. Let us focus on motivation. 

*Motivation*
The timeline plus chances considerations outlined above mean that the only direct paths are roundabout. There is no world where I simply dive into a bunch of papers and figure out aging. 
Lab, funding, education (leaving out credibility): these are necessary. And the only paths to them are long.

Motivation is a test of my cognitive wherewithal, then. 
Since I am motivated by directly working on the causes I care about, can I keep in mind
that the (Ph.D./startup) is the most direct route?

*** Why direct research, and why in a lab?
Why do direct research? Isn't it more efficient to hire someone else to do it?
Two reasons. First, without some personal input, I'm not sure someone else will do the
research I want to done. If you want something done, you have to do it yourself.
Second, I'm smart and motivated and can make a substantive marginal difference.

Why a lab? A thorough and creative look at the literature, along with data mining,
would be very important research. How many people are doing that? And in that case,
the world where we start solving the problem is a real one. Therefore, we should do that.

However, assuming that the literature does not hold the complete solution, then we need to conduct original
and physical research, and the statement that "there's no world where we just dive
in and solve this" holds true.

*** Chances and Timeline
In summary, chances of receiving lab and funding 
- Via government/university: low.
- Via doctorate + startup: higher.
- Via startup: moderate.

Timeline to researching stuff I care about.
- Via government/university: 2026. Ten years.
- Via doctorate + startup: 2026. (Get doctorate 2018 + 5 years, then 3 years for startup).
- Via startup: unknown. 2026. Five years to get running, five more years to get sufficient funding, etc.

There is also the possibility of combining these courses of action.
A master's is a good way to test the waters, as the first two years is a master's anyway.
Even if I started planning for Fall 2018 (applying January 2018), with more intensive
coursework, how will we live until then? A biotech startup would seem to be a logical
preparation for a master's or doctorate. It is a good story to tell.

*** What information would make the Ph.D. more necessary?
- Can we get funding or customers without a Ph.D.? Bearing in mind most biotech companies
are staffed almost entirely by Ph.D.'s.
- Can my role in the company include science, or will I be pushed out by inevitable internal
forces?
- Do we have, or can we acquire in time, the education and training necessary for a biotech startup?
- Perhaps I should be thinking 15-20 years out, rather than 10 years out. 
If the goal is to promote aging research in the long run, and realistically government-funded Big Science is the best way to accomplish that,
then a 10-year timeline may result in a local maxima.

*** Other impacts
Government funding has dropped, and if the private sector continues to grow in importance
for basic research, will continue to drop.
A company which hires many of the cheap and market-saturated doctorates available
has a marginal impact greater than a government lab, as that supply is fixed.

Much of scientific research - university or privately affiliated - is useless.
This can be fixed as a PI, privately or publicly funded. 

Does a private company afford more latitude and speed for scientific research?
Does it help free up the system to yet more entrepreneurs without formal training?

*** Intangible considerations
- The prestige of a Ph.D.
In addition to the real advantages of credibility - which could make a physical sciences Ph.D. worthwhile, which would be faster than a life sciences Ph.D. - I also would like to be in the club, without having to struggle uphill for years.
- Grad school
Further, being paid to learn and to discover new things sounds great. That's grad school's dirty secret: for those who like it, it is awesome.
- Working with Rhiannon
Splitting up to figure out a new startup, for her, and to spend all my time on a more lonely quest, for me, is not as much fun as working together.
