#+BEGIN_HTML
---
layout: post
title: Philosophy Games
date: 2017-09-01 12:38
# Should be longer than 20 words, so it will appear as post summary
description: Life with and without overlays
# tags will also be used as html meta keywords.
tags:
  - 

show_meta: true
comments: true
mathjax: true
gistembed: true
published: true
noindex: false
nofollow: false
---
#+END_HTML

** Games We Play
Once I saw someone tweet, "I can't believe I've got to go on washing and feeding
this body until I die," an extreme version of a more common feeling of
impatience at time wasted in crapping, brushing teeth, exercising, grocery
shopping, washing, eating unless it is social.

Several schools of philosophy offer us games to play to while away the time we
must spend in activities we don't care about. They are sort of overlays,
semi-transparent maps one places over the messiness of life. 

One such game is stoicism, or neo-stoicism. Bored, in pain, insulted? Well,
you're practicing for harder times! Everything you endure now can harden you for
when the times get really tough. 

Bad times are at once a challenge to your character and an opportunity to build
a better one. If you remember that good times will also pass, they are also an
opportunity to practice gratitude and an awareness of the passage of time. Both
can help us to let go of the artificial and reach for the (Platonic) real.

The common bits of life acquire a higher purpose by having a lower relative place:
don't worry about the passage of time, the task isn't the point, the point is
its role in the larger game.

Another game is meditation. If you are riding in a slow elevator, you can
practice sharpening your awareness of your mental and physical sensations, or
you can practice your equanimity toward these sensations, or your concentration
on these sensations, or all three. No time need be wasted.

Actually there are many such layers to place over life, to reveal or block the
underlying reality. If you are religious you can "pray always," if mathematical
or musical you can compose theories or harmonies.

** Protestant Excellence
All of these games help one not to obsess about what one should be doing, or to
feel bored, which is much the same thing. Of these games I prefer the meditation
one, generally, as one of the more intellectually and morally stimulating.

Of course, there's a certain element of the Protestant work ethic in this whole
dialogue, or of a too-credulous assent to economic pigeonholing. You don't need
to be a Marxist to worry about capitalist reductionism. But that's a
well-trodden critique, and anyway I can't help having some goals.

Lately I feel less bored by default. I credit Alex Pang's book /Rest/ for
this. Excellence isn't obtained after 10,000 hours of work, pure and simple. You
can only deliberately practice for about 4 hours a day, and to recover you must
rest like the best.

Mastery is achieved after 10,000 hours of deliberate practice, 12,500 hours of
deliberate rest, and 30,000 hours of sleep.

No time is wasted, then. The hours you spend away from your work are also
"productive." Being a person is your preparation for whatever else you want to
be. Even without an overlay, and even evaluated by its contribution toward a set of
well-defined goals, regular experience has value. 

And I also find that this relaxed attitude toward rest and recreation - the
higher value I now place on it - in the end moves beyond its utility toward this
set of well-defined goals. Now that I'm getting into the habit of appreciating
fallow time for its contribution toward certain goals, I find myself
appreciating the time for itself.

